# This is a basic workflow to help you get started with Actions

name: Version

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master, main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # - name: Use Node.js ${{ matrix.node-version }}
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: ${{ matrix.node-version }}

      # - name: Config
      #   run: npm config set @aaa-ncnu-ie:registry https://npm.pkg.github.com/aaa-ncnu-ie && npm config set //npm.pkg.github.com/:_authToken ${NPM_AUTH_TOKEN}
      #   env:
      #     NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      # # Install dependencies
      # - name: Install
      #   run: npm i --cache /tmp/empty-cache

      # # Make sure at a minimum that the Typescript compiles
      # - name: Build
      #   run: CI=false npm run build

      # # Runs the unit tests
      # - name: Unit Tests
      #   run: CI=true npm test

      - name: Update
        run: echo $(date) > test.txt && git add . && git commit -m "Update" && git push

      - uses: EndBug/add-and-commit@latest